name: Streamlink

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  streamlink-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Streamlink
        run: |
          pip install streamlink

      - name: Install Cloudflare WARP
        run: |
          sudo apt update
          sudo apt install -y curl
          curl https://pkg.cloudflareclient.com/pubkey.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list
          sudo apt update
          sudo apt install -y cloudflare-warp
          sudo warp-cli --accept-tos registration new
          sudo warp-cli --accept-tos connect
          sleep 5
          sudo warp-cli --accept-tos status

      - name: check stream (Kick)
        id: wait_stream_offline1
        run: |
          STREAM_URL="https://kick.com/vortex-ktv"
          echo "Checking stream status for $STREAM_URL"
          set +e
          if true; then
            STATUS_MSG=$(streamlink --json $STREAM_URL worst 2>&1)
            if echo "$STATUS_MSG" | grep -q "No playable streams found"; then
              echo "Stream is offline."
            else
              OUTFILE="/tmp/stream.ts"
              streamlink $STREAM_URL worst -o "$OUTFILE" > streamlink.log 2>&1 &
              STREAMLINK_PID=$!
              echo "Started streamlink with PID $STREAMLINK_PID"
              wait $STREAMLINK_PID
              EXIT_CODE=$?
              echo "Streamlink exited with code $EXIT_CODE"
              cat streamlink.log
              echo "$STATUS_MSG"
              echo "Stream is still online. Checking again in 60 seconds..."
              sleep 60
            fi
          fi
          set -e

      - name: check stream (Twitch)
        id: wait_stream_offline
        run: |
          STREAM_URL="https://twitch.tv/vortex-ktv"
          echo "Checking stream status for $STREAM_URL"
          set +e
          if true; then
            STATUS_MSG=$(streamlink --json $STREAM_URL worst 2>&1)
            if echo "$STATUS_MSG" | grep -q "No playable streams found"; then
              echo "Stream is offline."
            else
              OUTFILE="/tmp/stream.ts"
              streamlink $STREAM_URL worst -o "$OUTFILE" > streamlink.log 2>&1 &
              STREAMLINK_PID=$!
              echo "Started streamlink with PID $STREAMLINK_PID"
              wait $STREAMLINK_PID
              EXIT_CODE=$?
              echo "Streamlink exited with code $EXIT_CODE"
              cat streamlink.log
              echo "$STATUS_MSG"
              echo "Stream is still online. Checking again in 60 seconds..."
              sleep 60
            fi
          fi
          set -e
